version: '3'
services:
  appwrite:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    environment:
      # Add any necessary environment variables here
      - APPWRITE_DB_HOST=db
      - APPWRITE_DB_USER=my_db_user
      - APPWRITE_DB_PASS=my_db_password
      # Add other environment variables as needed

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: my_db_root_password
      MYSQL_DATABASE: my_db_name
      MYSQL_USER: my_db_user
      MYSQL_PASSWORD: my_db_password
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
